FROM python:3.11-slim

WORKDIR /mlflow


RUN pip install mlflow

ENV BACKEND_URI sqlite:///mlflow.db

EXPOSE 5000

CMD mlflow ui --backend-store-uri $BACKEND_URI --host 0.0.0.0
# CMD mlflow ui --backend-store-uri $BACKEND_URI--host 127.0.0.1
# # CMD mlflow server -h 0.0.0.0  --backend-store-uri sqlite:///mlflow.db  --default-artifact-root S3://airdemobkt
# CMD mlflow ui  --backend-store-uri sqlite:///mlflow.db  --default-artifact-root ./mlflow-artifact --host 127.0.0.1 --port 5000