FROM apache/airflow:latest

RUN pip install -U pip --upgrade pip
# RUN pip install mlflow

COPY requirements.txt /requirements.txt

# RUN pip install --no-cache-dir --user -r /requirements.txt
RUN pip install connexion[swagger-ui]
RUN pip install -r /requirements.txt