channels:
- conda-forge
dependencies:
- python=3.8.2
- pip<=19.2.3
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
